export const mockSalonInfo = {
    id: 1,
    name: 'Salon CoiffPro',
    address: '123 rue de la Coiffure, 75001 Paris',
    phone: '01 23 45 67 89',
    email: 'contact@coiffpro.fr',
    website: 'https://coiffpro.fr',
    openingHours: {
        monday: { open: '09:00', close: '19:00' },
        tuesday: { open: '09:00', close: '19:00' },
        wednesday: { open: '09:00', close: '19:00' },
        thursday: { open: '09:00', close: '19:00' },
        friday: { open: '09:00', close: '19:00' },
        saturday: { open: '09:00', close: '17:00' },
        sunday: { open: null, close: null },
    },
    services: [
        {
            id: 1,
            name: 'Coupe Homme',
            duration: 30,
            price: 25,
            category: 'coupe',
        },
        {
            id: 2,
            name: 'Coupe Femme',
            duration: 45,
            price: 35,
            category: 'coupe',
        },
        {
            id: 3,
            name: 'Coloration',
            duration: 90,
            price: 65,
            category: 'coloration',
        },
        {
            id: 4,
            name: 'Brushing',
            duration: 45,
            price: 40,
            category: 'coiffure',
        },
    ],
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
}
